# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - demodockerapphcl

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://azdemorg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c756fd2bcd244cb9bfa47b04a85aa0ef }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4d951cf161274d70a6f4eb4bab2af67c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: azdemorg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c756fd2bcd244cb9bfa47b04a85aa0ef }}/myregistrytest1993/webimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'demodockerapphcl'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_82208c1ca71744f190902acd882da234 }}
        images: 'azdemorg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c756fd2bcd244cb9bfa47b04a85aa0ef }}/myregistrytest1993/webimage:${{ github.sha }}'